### ISSUE TITLE
[BUG] Cast bar text needs truncation 

### ISSUE THREAD

**Issue by brandonjpierce** [Hydra-WoW/vUI#13]
Might be cool to base it off of the castbar width

![thing](https://user-images.githubusercontent.com/5483779/65478003-b7434d00-de4d-11e9-8363-3695e0bebba3.png)

**Comment by Hydra-WoW** [comment]
Pushed a change for this, let me know how it looks to you

**Comment by brandonjpierce** [comment]
@Hydra-WoW just a follow up on this: I haven't found a long enough cast text to fully test this again but I am going to assume it is fixed now!
