### ISSUE TITLE
[BUG] Experience progress text

### ISSUE THREAD

**Issue by brandonjpierce** [Hydra-WoW/vUI#3]
From user `FreaK`:

> another issue with the xp bar, i have % on right right side but a lot of times a number gets stuck there like for example 55.6%, and then the actually % continues to increase from there and they are just overlapping each other

**Comment by Hydra-WoW** [comment]
I haven't been able to reproduce this yet. Not being able to see what's happening makes this one hard to nail down.

**Comment by brandonjpierce** [comment]
Agreed think we will need some more info from FreaK on this as I was not able to repro either.

**Comment by brandonjpierce** [comment]
No additional info from FreaK, closing for now.
