### ISSUE TITLE
[BUG] Experience bar position

### ISSUE THREAD

**Issue by brandonjpierce** [Hydra-WoW/vUI#4]
From user `FreaK`: 

> and the XP bar is stuck to the top of the screen as well even though its set to classic position, and i cant change it to anything else, its stuck on that option

**Comment by Hydra-WoW** [comment]
This and the Cast Bar Position report are likely both linked to a mistake I had in early movers. Restoring movers to default while using current versions should fix it for the users.

**Comment by brandonjpierce** [comment]
@Hydra-WoW sounds good I'll ping FreaK and see if he can verify this is no longer occurring

**Comment by brandonjpierce** [comment]
No additional info from FreaK, closing for now.
